import mongoose, { Schema, type Model, type Types } from "mongoose";
import {
  TASK_PRIORITIES,
  TASK_STATUSES,
  TASK_TYPES,
  type TaskPriority,
  type TaskStatus,
  type TaskType,
} from "@/lib/constants";

export interface IHousekeepingTask {
  _id: Types.ObjectId;
  taskCode: string;
  room: Types.ObjectId;
  reservation?: Types.ObjectId | null;
  type: TaskType;
  status: TaskStatus;
  priority: TaskPriority;
  assignedTo?: Types.ObjectId | null;
  scheduledFor: Date;
  startedAt?: Date | null;
  completedAt?: Date | null;
  notes?: string;
  inspectionNotes?: string;
  createdBy?: Types.ObjectId | null;
  completedBy?: Types.ObjectId | null;
  createdAt: Date;
  updatedAt: Date;
}

const HousekeepingTaskSchema = new Schema<IHousekeepingTask>(
  {
    taskCode: { type: String, required: true, unique: true, trim: true, uppercase: true },
    room: { type: Schema.Types.ObjectId, ref: "Room", required: true, index: true },
    // Set when the task was generated by a check-out, so the folio can be traced.
    reservation: { type: Schema.Types.ObjectId, ref: "Reservation", default: null },
    type: { type: String, enum: TASK_TYPES, default: "CLEANING", index: true },
    status: { type: String, enum: TASK_STATUSES, default: "PENDING", index: true },
    priority: { type: String, enum: TASK_PRIORITIES, default: "NORMAL", index: true },
    assignedTo: { type: Schema.Types.ObjectId, ref: "Staff", default: null, index: true },
    scheduledFor: { type: Date, required: true, default: () => new Date(), index: true },
    startedAt: { type: Date, default: null },
    completedAt: { type: Date, default: null },
    notes: { type: String, trim: true, maxlength: 2000 },
    inspectionNotes: { type: String, trim: true, maxlength: 2000 },
    createdBy: { type: Schema.Types.ObjectId, ref: "User", default: null },
    completedBy: { type: Schema.Types.ObjectId, ref: "User", default: null },
  },
  { timestamps: true },
);

HousekeepingTaskSchema.index({ status: 1, scheduledFor: 1 });
HousekeepingTaskSchema.index({ assignedTo: 1, status: 1 });

export const HousekeepingTask: Model<IHousekeepingTask> =
  (mongoose.models.HousekeepingTask as Model<IHousekeepingTask>) ||
  mongoose.model<IHousekeepingTask>("HousekeepingTask", HousekeepingTaskSchema);

export default HousekeepingTask;
